### ISSUE TITLE
After Name Change cannot Set new Leader

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/faf.webapp#65]
```
change clan leader
Sent: Today, 13:52
by ABSTRACT

Hi Dragonfire, i want to ask how i can change the leader of a clan. If i press the "change Leader" button, select a member of my clan, and try to change it, i get the message "new leader it not in this clan". There are different names for founder and leader btw. My old name for leader, and my actual name for founder.

Ist the same Account but different namens. Deathbringer is not the current name, it is Littlesunshine. 
Atm i just want to make my other acc to Clan leader (ABSTRACT). I invited myself to the Clan and accepted the request. But as Littlesunshine i cant make ABSTRACT to leader.
```

**Comment by Nonemoticoner** [comment]
>There are different names for founder and leader btw

Well, we know about this since a while, but I viewed BC clan page recently and there must be something wrong: http://www.faforever.com/clans/clan_24
It used to be (atleast when we released first version of app):

**Founder:** BC_Blackheart *(name of founder when creating clan)*
**Leader:** DoctorDog *(current name of leader)*

Now, it's reversed and maybe this couses the problem. Also, if fixed, we should change that string for founder into some pointer to exact player. Or remove it literally because it's been added as something that would be remembering about the first creator of clan in case he quited game and gave someone leader etc. Not that useful, really.

**Comment by IDragonfire** [comment]
Founder was the initial design from "thebeej"
As I remember it is only the "name" of the creator, not linked to an account ...

**Comment by Nonemoticoner** [comment]
Yes, it was. But this makes things confusing, because FAF allows nick-changing (what's not that best idea at all).

Currently, the main problem is that someone reversed leader with founder. Atleast, it's mistaken in front-end view. Dunno how it looks in the back-end.

**Comment by IDragonfire** [comment]
That is a issue fix, switch founder to the end ...

**Comment by IDragonfire** [comment]
This issue was moved to FAForever/faf.webapp#2

**Comment by IDragonfire** [comment]
This issue was moved to FAForever/faf.webapp#3

**Comment by IDragonfire** [comment]
This issue was moved to FAForever/faf.webapp#4
